name: Deploy to GitHub pages
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: marceloprado/has-changed-path@v1
        id: changed-docs
        with:
          paths: docs
      - name: Generate static vuevite files
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run docs:build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/.vitepress/dist
          git init
          git add -A
          git commit -m 'chore(docs): update docs'
          git push -f git@github.com:wangkaiwd/typescript-axios.git master:gh-pages
          cd -
