name: Deploy to GitHub pages
on:
  push:
    branches: [ main, master ]
#    paths:
#      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}
      - name: Generate static docs files
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run docs:build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/.vitepress/dist
          git config --global user.email "1162486176@qq.com"
          git config --global user.name "wangkaiwd"
          git init
          git add .
          git commit -m 'chore(docs): update docs'
          git push -f https://github.com/typescript-axios.git master:gh-pages
          cd -
